{{- with .Values.watchdogConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: velero-watchdog-config
  labels:
  {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
stringData:
  SLACK_TOKEN: {{ .slackToken | quote }}
  EMAIL_PASSWORD: {{ .emailPassword | quote }}
  TELEGRAM_TOKEN: {{ .telegramToken | quote }}
{{- end }}
