{{- with .Values.apiConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: velero-api-config
  labels:
  {{- include "seriohub-velero.labels" $ | nindent 4 }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .awsSecretAccessKey | quote }}
  RESTIC_PASSWORD: {{ .resticPassword | quote }}
  SECURITY_PATH_DATABASE: {{ .securityPathDatabase | quote }}
  {{- if not (quote .securityTokenKey | empty)  }}
  SECURITY_TOKEN_KEY: {{ .securityTokenKey }}
  {{- end }}
{{- end }}