{{- if .Values.uiIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-ingress
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  {{- with .Values.uiIngress.metadata.annotations }}
  annotations:
    {{- . | toYaml | nindent 4}}
  {{- end }}
spec:
  ingressClassName: {{ .Values.uiIngress.ingressClassName }}
  rules:
  - host: {{ .Values.uiIngress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "seriohub-velero.fullname" . }}-ui'
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "seriohub-velero.fullname" . }}-api'
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "seriohub-velero.fullname" . }}-api'
            port:
              number: 80
        path: /ws
        pathType: Prefix
<<<<<<< HEAD:chart/templates/50_ingress.yaml
=======
      - backend:
          service:
            name: '{{ include "seriohub-velero.fullname" . }}-ui'
            port:
              number: 80
        path: /
        pathType: Prefix
  {{- if not .Values.uiIngress.spec.tls }}
  tls: []
  {{- else }}
>>>>>>> 6ced3eb5e2a7403570a91b2e4b61161e1f3c10b9:chart/templates/150_vui_ingress.yaml
  tls:
  {{- if .Values.uiIngress.spec.tls }}
    {{- .Values.uiIngress.spec.tls | toYaml | nindent 2 }}
  {{- end }}
  {{- if .Values.uiIngress.tls.enabled }}
  - hosts:
      - {{ .Values.uiIngress.host }}
    secretName: {{ include "seriohub-velero.fullname" . }}-api-tls
  {{- end }}
{{- end }}
