{{- if .Values.uiIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-ingress
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.uiIngress.ingressClassName }}
  rules:
  - host: {{ .Values.uiIngress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "seriohub-velero.fullname" . }}-api'
            port:
              number: 80
        path: /api
        pathType: Prefix
      - backend:
          service:
            name: '{{ include "seriohub-velero.fullname" . }}-api'
            port:
              number: 80
        path: /ws
        pathType: Prefix
  {{- if not .Values.uiIngress.spec.tls }}
  tls: []
  {{- else }}
  {{- .Values.uiIngress.spec.tls | toYaml | nindent 2 }}
  {{- end }}
{{- end }}
