apiVersion: v1
kind: ConfigMap
metadata:
  name: velero-ui-config
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
data:
  NEXT_PUBLIC_REFRESH_DATATABLE_AFTER: {{ .Values.uiConfig.nextPublicRefreshDatatableAfter
    | quote }}
  NEXT_PUBLIC_REFRESH_RECENT: {{ .Values.uiConfig.nextPublicRefreshRecent | quote
    }}
  NEXT_PUBLIC_VELERO_API_URL: {{ .Values.uiConfig.nextPublicVeleroApiUrl | quote
    }}
  NEXT_PUBLIC_VELERO_API_WS: {{ .Values.uiConfig.nextPublicVeleroApiWs | quote }}