{{- if .Values.apiConfig.storage.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-api
spec:
  storageClassName: {{ .Values.apiConfig.storage.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- end }}
