apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-mgmt-role
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Values.global.veleroNamespace }}
rules:
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-mgmt-role
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - '*'