apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-mgmt-role-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
  namespace: {{ .Values.global.veleroNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "seriohub-velero.fullname" . }}-mgmt-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "seriohub-velero.fullname" . }}-api-sa'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-role-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "seriohub-velero.fullname" . }}-api-mgmt-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "seriohub-velero.fullname" . }}-api-sa'
  namespace: '{{ .Release.Namespace }}'