apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api
  labels:
    app: velero-api
    layer: api
    tier: backend
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: velero-api
      layer: api
      tier: backend
    {{- include "seriohub-velero.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: velero-api
        layer: api
        tier: backend
      {{- include "seriohub-velero.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        envFrom:
        - configMapRef:
            name: velero-api-config
        image: {{ .Values.api.apiServer.image.repository }}:{{ .Values.api.apiServer.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.apiServer.imagePullPolicy }}
        name: api-server
        ports:
        - containerPort: 8001
          name: api
        resources: {}
      serviceAccountName: {{ include "seriohub-velero.fullname" . }}-api-sa