{{- if .Values.apiIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-api-ingress
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.apiIngress.host }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "seriohub-velero.fullname" . }}-api'
            port:
              number: 80
        path: /
        pathType: Prefix
{{- end }}
