apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-mgmt-cluster-role
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - watch
  - list
- apiGroups: 
  - "velero.io"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "seriohub-velero.fullname" . }}-mgmt-cluster-role-binding
  labels:
  {{- include "seriohub-velero.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ include "seriohub-velero.fullname" . }}-mgmt-cluster-role"
subjects:
- kind: ServiceAccount
  name: "{{ include "seriohub-velero.fullname" . }}-api-sa"
  namespace: "{{ .Release.Namespace }}"