apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-mgmt-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: velero-api-sa
    namespace: velero-ui
roleRef:
  kind: ClusterRole
  name: velero-mgmt-cluster-role
  apiGroup: rbac.authorization.k8s.io
