apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-mgmt-role-binding
  namespace: velero
subjects:
- kind: ServiceAccount
  name: velero-api-sa
  namespace: velero-ui
roleRef:
  kind: Role
  name: velero-mgmt-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-api-role-binding
  namespace: velero-ui
subjects:
- kind: ServiceAccount
  name: velero-api-sa
  namespace: velero-ui
roleRef:
  kind: Role
  name: velero-api-mgmt-role
  apiGroup: rbac.authorization.k8s.io
